/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jSampleJniCall1 */

#ifndef _Included_jSampleJniCall1
#define _Included_jSampleJniCall1
#ifdef __cplusplus
extern "C" {
#endif
#undef jSampleJniCall1_JNI_RETURN_OK
#define jSampleJniCall1_JNI_RETURN_OK 0L
#undef jSampleJniCall1_JNI_RETURN_NG
#define jSampleJniCall1_JNI_RETURN_NG -1L
/*
 * Class:     jSampleJniCall1
 * Method:    sampleJniCall1
 * Signature: (Ljava/lang/String;[B[B[B)I
 */
JNIEXPORT jint JNICALL Java_jSampleJniCall1_sampleJniCall1
  (JNIEnv *, jobject, jstring, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     jSampleJniCall1
 * Method:    sampleJniCall2
 * Signature: (Ljava/lang/String;Ljava/lang/String;[B[B[B)I
 */
JNIEXPORT jint JNICALL Java_jSampleJniCall1_sampleJniCall2
  (JNIEnv *, jobject, jstring, jstring, jbyteArray, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
