/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JSampleJniCall1 */

#ifndef _Included_JSampleJniCall1
#define _Included_JSampleJniCall1
#ifdef __cplusplus
extern "C" {
#endif
#undef JSampleJniCall1_JNI_RETURN_OK
#define JSampleJniCall1_JNI_RETURN_OK 0L
#undef JSampleJniCall1_JNI_RETURN_NG
#define JSampleJniCall1_JNI_RETURN_NG -1L
/*
 * Class:     JSampleJniCall1
 * Method:    sampleJniCall1
 * Signature: (Ljava/lang/String;[B[B[B)I
 */
JNIEXPORT jint JNICALL Java_JSampleJniCall1_sampleJniCall1
  (JNIEnv *, jobject, jstring, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     JSampleJniCall1
 * Method:    sampleJniCall2
 * Signature: (Ljava/lang/String;Ljava/lang/String;[B[B[B)I
 */
JNIEXPORT jint JNICALL Java_JSampleJniCall1_sampleJniCall2
  (JNIEnv *, jobject, jstring, jstring, jbyteArray, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
